//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantriesProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInfo
    {
        public int Id { get; set; }
        public string SelerName { get; set; }
        public Nullable<System.DateTime> SelerDate { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    }
}
