//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantriesProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int S_Id { get; set; }
        public string S_Name { get; set; }
        public string S_Address { get; set; }
        public Nullable<int> S_NID { get; set; }
        public Nullable<System.DateTime> S_DateOfBirth { get; set; }
        public Nullable<System.DateTime> S_JoinDate { get; set; }
        public Nullable<int> S_Phone { get; set; }
        public string S_Username { get; set; }
        public string S_Password { get; set; }
    }
}
